# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'qsm_window.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1036, 630)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.stackedWidget_data = QtWidgets.QStackedWidget(self.centralwidget)
        self.stackedWidget_data.setGeometry(QtCore.QRect(0, 0, 281, 551))
        self.stackedWidget_data.setObjectName("stackedWidget_data")
        self.page_main = QtWidgets.QWidget()
        self.page_main.setObjectName("page_main")
        self.toolBox_main = QtWidgets.QToolBox(self.page_main)
        self.toolBox_main.setGeometry(QtCore.QRect(10, 10, 261, 441))
        self.toolBox_main.setObjectName("toolBox_main")
        self.page_data = QtWidgets.QWidget()
        self.page_data.setGeometry(QtCore.QRect(0, 0, 261, 387))
        self.page_data.setObjectName("page_data")
        self.treeWidget_data = QtWidgets.QTreeWidget(self.page_data)
        self.treeWidget_data.setGeometry(QtCore.QRect(0, 0, 261, 351))
        self.treeWidget_data.setObjectName("treeWidget_data")
        item_0 = QtWidgets.QTreeWidgetItem(self.treeWidget_data)
        item_0 = QtWidgets.QTreeWidgetItem(self.treeWidget_data)
        item_0 = QtWidgets.QTreeWidgetItem(self.treeWidget_data)
        item_0 = QtWidgets.QTreeWidgetItem(self.treeWidget_data)
        item_0 = QtWidgets.QTreeWidgetItem(self.treeWidget_data)
        item_0 = QtWidgets.QTreeWidgetItem(self.treeWidget_data)
        item_0 = QtWidgets.QTreeWidgetItem(self.treeWidget_data)
        self.treeWidget_data.header().setDefaultSectionSize(120)
        self.radioButton_data_left = QtWidgets.QRadioButton(self.page_data)
        self.radioButton_data_left.setGeometry(QtCore.QRect(70, 360, 41, 17))
        self.radioButton_data_left.setChecked(True)
        self.radioButton_data_left.setObjectName("radioButton_data_left")
        self.radioButton_data_right = QtWidgets.QRadioButton(self.page_data)
        self.radioButton_data_right.setGeometry(QtCore.QRect(140, 360, 51, 17))
        self.radioButton_data_right.setObjectName("radioButton_data_right")
        self.toolBox_main.addItem(self.page_data, "")
        self.page_parameters = QtWidgets.QWidget()
        self.page_parameters.setGeometry(QtCore.QRect(0, 0, 261, 387))
        self.page_parameters.setObjectName("page_parameters")
        self.treeWidget_parameters = QtWidgets.QTreeWidget(self.page_parameters)
        self.treeWidget_parameters.setGeometry(QtCore.QRect(0, 0, 261, 351))
        self.treeWidget_parameters.setObjectName("treeWidget_parameters")
        item_0 = QtWidgets.QTreeWidgetItem(self.treeWidget_parameters)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1.setFlags(QtCore.Qt.ItemIsSelectable|QtCore.Qt.ItemIsEditable|QtCore.Qt.ItemIsDragEnabled|QtCore.Qt.ItemIsUserCheckable|QtCore.Qt.ItemIsEnabled)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1.setFlags(QtCore.Qt.ItemIsSelectable|QtCore.Qt.ItemIsEditable|QtCore.Qt.ItemIsDragEnabled|QtCore.Qt.ItemIsUserCheckable|QtCore.Qt.ItemIsEnabled)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1.setFlags(QtCore.Qt.ItemIsSelectable|QtCore.Qt.ItemIsEditable|QtCore.Qt.ItemIsDragEnabled|QtCore.Qt.ItemIsUserCheckable|QtCore.Qt.ItemIsEnabled)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1.setFlags(QtCore.Qt.ItemIsSelectable|QtCore.Qt.ItemIsEditable|QtCore.Qt.ItemIsDragEnabled|QtCore.Qt.ItemIsUserCheckable|QtCore.Qt.ItemIsEnabled)
        item_0 = QtWidgets.QTreeWidgetItem(self.treeWidget_parameters)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1.setFlags(QtCore.Qt.ItemIsSelectable|QtCore.Qt.ItemIsEditable|QtCore.Qt.ItemIsDragEnabled|QtCore.Qt.ItemIsUserCheckable|QtCore.Qt.ItemIsEnabled)
        item_0 = QtWidgets.QTreeWidgetItem(self.treeWidget_parameters)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1.setFlags(QtCore.Qt.ItemIsSelectable|QtCore.Qt.ItemIsEditable|QtCore.Qt.ItemIsDragEnabled|QtCore.Qt.ItemIsUserCheckable|QtCore.Qt.ItemIsEnabled)
        item_0 = QtWidgets.QTreeWidgetItem(self.treeWidget_parameters)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1.setFlags(QtCore.Qt.ItemIsSelectable|QtCore.Qt.ItemIsEditable|QtCore.Qt.ItemIsDragEnabled|QtCore.Qt.ItemIsUserCheckable|QtCore.Qt.ItemIsEnabled)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1.setFlags(QtCore.Qt.ItemIsSelectable|QtCore.Qt.ItemIsEditable|QtCore.Qt.ItemIsDragEnabled|QtCore.Qt.ItemIsUserCheckable|QtCore.Qt.ItemIsEnabled)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1.setFlags(QtCore.Qt.ItemIsSelectable|QtCore.Qt.ItemIsEditable|QtCore.Qt.ItemIsDragEnabled|QtCore.Qt.ItemIsUserCheckable|QtCore.Qt.ItemIsEnabled)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1.setFlags(QtCore.Qt.ItemIsSelectable|QtCore.Qt.ItemIsEditable|QtCore.Qt.ItemIsDragEnabled|QtCore.Qt.ItemIsUserCheckable|QtCore.Qt.ItemIsEnabled)
        self.treeWidget_parameters.header().setDefaultSectionSize(150)
        self.toolBox_main.addItem(self.page_parameters, "")
        self.pushButton_create_mask = QtWidgets.QPushButton(self.page_main)
        self.pushButton_create_mask.setGeometry(QtCore.QRect(10, 460, 81, 31))
        self.pushButton_create_mask.setObjectName("pushButton_create_mask")
        self.pushButton_unwrap_phase = QtWidgets.QPushButton(self.page_main)
        self.pushButton_unwrap_phase.setGeometry(QtCore.QRect(100, 460, 81, 31))
        self.pushButton_unwrap_phase.setObjectName("pushButton_unwrap_phase")
        self.pushButton_v_sharp = QtWidgets.QPushButton(self.page_main)
        self.pushButton_v_sharp.setGeometry(QtCore.QRect(190, 460, 81, 31))
        self.pushButton_v_sharp.setObjectName("pushButton_v_sharp")
        self.pushButton_qsm_star = QtWidgets.QPushButton(self.page_main)
        self.pushButton_qsm_star.setGeometry(QtCore.QRect(10, 500, 81, 31))
        self.pushButton_qsm_star.setObjectName("pushButton_qsm_star")
        self.pushButton_qsm_ics = QtWidgets.QPushButton(self.page_main)
        self.pushButton_qsm_ics.setGeometry(QtCore.QRect(100, 500, 81, 31))
        self.pushButton_qsm_ics.setObjectName("pushButton_qsm_ics")
        self.stackedWidget_data.addWidget(self.page_main)
        self.page_contrast = QtWidgets.QWidget()
        self.page_contrast.setObjectName("page_contrast")
        self.frame_contrast = QtWidgets.QFrame(self.page_contrast)
        self.frame_contrast.setGeometry(QtCore.QRect(10, 10, 261, 201))
        self.frame_contrast.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_contrast.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_contrast.setObjectName("frame_contrast")
        self.label = QtWidgets.QLabel(self.page_contrast)
        self.label.setGeometry(QtCore.QRect(10, 220, 41, 16))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.page_contrast)
        self.label_2.setGeometry(QtCore.QRect(10, 250, 41, 16))
        self.label_2.setObjectName("label_2")
        self.horizontalSlider_center = QtWidgets.QSlider(self.page_contrast)
        self.horizontalSlider_center.setGeometry(QtCore.QRect(50, 220, 160, 19))
        self.horizontalSlider_center.setProperty("value", 49)
        self.horizontalSlider_center.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider_center.setObjectName("horizontalSlider_center")
        self.horizontalSlider_range = QtWidgets.QSlider(self.page_contrast)
        self.horizontalSlider_range.setGeometry(QtCore.QRect(50, 250, 160, 19))
        self.horizontalSlider_range.setProperty("value", 49)
        self.horizontalSlider_range.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider_range.setObjectName("horizontalSlider_range")
        self.pushButton_contrast_auto = QtWidgets.QPushButton(self.page_contrast)
        self.pushButton_contrast_auto.setGeometry(QtCore.QRect(10, 300, 75, 23))
        self.pushButton_contrast_auto.setObjectName("pushButton_contrast_auto")
        self.pushButton_contrast_ok = QtWidgets.QPushButton(self.page_contrast)
        self.pushButton_contrast_ok.setGeometry(QtCore.QRect(100, 300, 75, 23))
        self.pushButton_contrast_ok.setObjectName("pushButton_contrast_ok")
        self.pushButton_contrast_cancel = QtWidgets.QPushButton(self.page_contrast)
        self.pushButton_contrast_cancel.setGeometry(QtCore.QRect(190, 300, 75, 23))
        self.pushButton_contrast_cancel.setObjectName("pushButton_contrast_cancel")
        self.radioButton_contrast_left = QtWidgets.QRadioButton(self.page_contrast)
        self.radioButton_contrast_left.setGeometry(QtCore.QRect(80, 270, 41, 17))
        self.radioButton_contrast_left.setChecked(True)
        self.radioButton_contrast_left.setObjectName("radioButton_contrast_left")
        self.radioButton_contrast_right = QtWidgets.QRadioButton(self.page_contrast)
        self.radioButton_contrast_right.setGeometry(QtCore.QRect(140, 270, 51, 17))
        self.radioButton_contrast_right.setObjectName("radioButton_contrast_right")
        self.doubleSpinBox_center = QtWidgets.QDoubleSpinBox(self.page_contrast)
        self.doubleSpinBox_center.setGeometry(QtCore.QRect(220, 220, 62, 21))
        self.doubleSpinBox_center.setObjectName("doubleSpinBox_center")
        self.doubleSpinBox_range = QtWidgets.QDoubleSpinBox(self.page_contrast)
        self.doubleSpinBox_range.setGeometry(QtCore.QRect(220, 250, 62, 21))
        self.doubleSpinBox_range.setObjectName("doubleSpinBox_range")
        self.stackedWidget_data.addWidget(self.page_contrast)
        self.stackedWidget_image = QtWidgets.QStackedWidget(self.centralwidget)
        self.stackedWidget_image.setGeometry(QtCore.QRect(280, 0, 751, 551))
        self.stackedWidget_image.setObjectName("stackedWidget_image")
        self.page_all = QtWidgets.QWidget()
        self.page_all.setObjectName("page_all")
        self.frame_all = QtWidgets.QFrame(self.page_all)
        self.frame_all.setGeometry(QtCore.QRect(10, 10, 741, 481))
        self.frame_all.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_all.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_all.setObjectName("frame_all")
        self.spinBox_all_x = QtWidgets.QSpinBox(self.page_all)
        self.spinBox_all_x.setGeometry(QtCore.QRect(10, 500, 61, 21))
        self.spinBox_all_x.setObjectName("spinBox_all_x")
        self.spinBox_all_y = QtWidgets.QSpinBox(self.page_all)
        self.spinBox_all_y.setGeometry(QtCore.QRect(80, 500, 61, 21))
        self.spinBox_all_y.setObjectName("spinBox_all_y")
        self.spinBox_all_z = QtWidgets.QSpinBox(self.page_all)
        self.spinBox_all_z.setGeometry(QtCore.QRect(150, 500, 61, 21))
        self.spinBox_all_z.setObjectName("spinBox_all_z")
        self.spinBox_all_v = QtWidgets.QSpinBox(self.page_all)
        self.spinBox_all_v.setGeometry(QtCore.QRect(220, 500, 61, 21))
        self.spinBox_all_v.setObjectName("spinBox_all_v")
        self.stackedWidget_image.addWidget(self.page_all)
        self.page_single = QtWidgets.QWidget()
        self.page_single.setObjectName("page_single")
        self.frame_single = QtWidgets.QFrame(self.page_single)
        self.frame_single.setGeometry(QtCore.QRect(10, 10, 741, 481))
        self.frame_single.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_single.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_single.setObjectName("frame_single")
        self.horizontalScrollBar_single_slice_left = QtWidgets.QScrollBar(self.page_single)
        self.horizontalScrollBar_single_slice_left.setGeometry(QtCore.QRect(90, 500, 241, 20))
        self.horizontalScrollBar_single_slice_left.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalScrollBar_single_slice_left.setObjectName("horizontalScrollBar_single_slice_left")
        self.spinBox_single_v = QtWidgets.QSpinBox(self.page_single)
        self.spinBox_single_v.setGeometry(QtCore.QRect(680, 500, 71, 21))
        self.spinBox_single_v.setObjectName("spinBox_single_v")
        self.spinBox_single_slice_left = QtWidgets.QSpinBox(self.page_single)
        self.spinBox_single_slice_left.setGeometry(QtCore.QRect(10, 500, 71, 21))
        self.spinBox_single_slice_left.setObjectName("spinBox_single_slice_left")
        self.spinBox_single_slice_right = QtWidgets.QSpinBox(self.page_single)
        self.spinBox_single_slice_right.setGeometry(QtCore.QRect(350, 500, 71, 21))
        self.spinBox_single_slice_right.setObjectName("spinBox_single_slice_right")
        self.horizontalScrollBar_single_slice_right = QtWidgets.QScrollBar(self.page_single)
        self.horizontalScrollBar_single_slice_right.setGeometry(QtCore.QRect(430, 500, 241, 20))
        self.horizontalScrollBar_single_slice_right.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalScrollBar_single_slice_right.setObjectName("horizontalScrollBar_single_slice_right")
        self.horizontalScrollBar_single_slice_both = QtWidgets.QScrollBar(self.page_single)
        self.horizontalScrollBar_single_slice_both.setGeometry(QtCore.QRect(240, 530, 271, 21))
        self.horizontalScrollBar_single_slice_both.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalScrollBar_single_slice_both.setObjectName("horizontalScrollBar_single_slice_both")
        self.stackedWidget_image.addWidget(self.page_single)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1036, 21))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        self.menuView = QtWidgets.QMenu(self.menubar)
        self.menuView.setObjectName("menuView")
        self.menuOrientation = QtWidgets.QMenu(self.menubar)
        self.menuOrientation.setObjectName("menuOrientation")
        self.menuHelp = QtWidgets.QMenu(self.menubar)
        self.menuHelp.setObjectName("menuHelp")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.toolBar = QtWidgets.QToolBar(MainWindow)
        self.toolBar.setObjectName("toolBar")
        MainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.toolBar)
        self.actionRead_Dicom = QtWidgets.QAction(MainWindow)
        self.actionRead_Dicom.setObjectName("actionRead_Dicom")
        self.actionAbout = QtWidgets.QAction(MainWindow)
        self.actionAbout.setObjectName("actionAbout")
        self.actionOpen = QtWidgets.QAction(MainWindow)
        self.actionOpen.setCheckable(True)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/images/01_open.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionOpen.setIcon(icon)
        self.actionOpen.setObjectName("actionOpen")
        self.actionSave = QtWidgets.QAction(MainWindow)
        self.actionSave.setCheckable(True)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/images/02_save.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionSave.setIcon(icon1)
        self.actionSave.setObjectName("actionSave")
        self.actionSave_All = QtWidgets.QAction(MainWindow)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/images/03_save_all.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionSave_All.setIcon(icon2)
        self.actionSave_All.setObjectName("actionSave_All")
        self.actionAxial = QtWidgets.QAction(MainWindow)
        self.actionAxial.setCheckable(True)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/images/04_axial.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionAxial.setIcon(icon3)
        self.actionAxial.setObjectName("actionAxial")
        self.actionSaggital = QtWidgets.QAction(MainWindow)
        self.actionSaggital.setCheckable(True)
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(":/images/05_saggital.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionSaggital.setIcon(icon4)
        self.actionSaggital.setObjectName("actionSaggital")
        self.actionCoronal = QtWidgets.QAction(MainWindow)
        self.actionCoronal.setCheckable(True)
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(":/images/06_coronal.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionCoronal.setIcon(icon5)
        self.actionCoronal.setObjectName("actionCoronal")
        self.actionAll_Orientations = QtWidgets.QAction(MainWindow)
        self.actionAll_Orientations.setCheckable(True)
        self.actionAll_Orientations.setChecked(False)
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap(":/images/07_all_orientations.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionAll_Orientations.setIcon(icon6)
        self.actionAll_Orientations.setObjectName("actionAll_Orientations")
        self.actionContrast = QtWidgets.QAction(MainWindow)
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap(":/images/08_contrast.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionContrast.setIcon(icon7)
        self.actionContrast.setObjectName("actionContrast")
        self.actionZoom_In = QtWidgets.QAction(MainWindow)
        self.actionZoom_In.setCheckable(True)
        icon8 = QtGui.QIcon()
        icon8.addPixmap(QtGui.QPixmap(":/images/09_zoom_in.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionZoom_In.setIcon(icon8)
        self.actionZoom_In.setObjectName("actionZoom_In")
        self.actionZoom_Out = QtWidgets.QAction(MainWindow)
        icon9 = QtGui.QIcon()
        icon9.addPixmap(QtGui.QPixmap(":/images/10_zoom_out.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionZoom_Out.setIcon(icon9)
        self.actionZoom_Out.setObjectName("actionZoom_Out")
        self.actionView = QtWidgets.QAction(MainWindow)
        self.actionView.setCheckable(True)
        icon10 = QtGui.QIcon()
        icon10.addPixmap(QtGui.QPixmap(":/images/11_view.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionView.setIcon(icon10)
        self.actionView.setObjectName("actionView")
        self.menuFile.addAction(self.actionOpen)
        self.menuFile.addAction(self.actionSave)
        self.menuFile.addAction(self.actionView)
        self.menuFile.addAction(self.actionSave_All)
        self.menuFile.addAction(self.actionRead_Dicom)
        self.menuView.addAction(self.actionZoom_In)
        self.menuView.addAction(self.actionZoom_Out)
        self.menuOrientation.addAction(self.actionAxial)
        self.menuOrientation.addAction(self.actionSaggital)
        self.menuOrientation.addAction(self.actionCoronal)
        self.menuOrientation.addAction(self.actionAll_Orientations)
        self.menuHelp.addAction(self.actionAbout)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuView.menuAction())
        self.menubar.addAction(self.menuOrientation.menuAction())
        self.menubar.addAction(self.menuHelp.menuAction())
        self.toolBar.addAction(self.actionOpen)
        self.toolBar.addAction(self.actionSave)
        self.toolBar.addAction(self.actionView)
        self.toolBar.addAction(self.actionSave_All)
        self.toolBar.addSeparator()
        self.toolBar.addAction(self.actionZoom_In)
        self.toolBar.addAction(self.actionZoom_Out)
        self.toolBar.addSeparator()
        self.toolBar.addAction(self.actionAxial)
        self.toolBar.addAction(self.actionSaggital)
        self.toolBar.addAction(self.actionCoronal)
        self.toolBar.addAction(self.actionAll_Orientations)

        self.retranslateUi(MainWindow)
        self.stackedWidget_data.setCurrentIndex(0)
        self.toolBox_main.setCurrentIndex(0)
        self.stackedWidget_image.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Susceptibility Imaging Toolkit (SITK)"))
        self.treeWidget_data.headerItem().setText(0, _translate("MainWindow", "Data"))
        self.treeWidget_data.headerItem().setText(1, _translate("MainWindow", "Size"))
        __sortingEnabled = self.treeWidget_data.isSortingEnabled()
        self.treeWidget_data.setSortingEnabled(False)
        self.treeWidget_data.topLevelItem(0).setText(0, _translate("MainWindow", "Magnitude"))
        self.treeWidget_data.topLevelItem(1).setText(0, _translate("MainWindow", "Phase"))
        self.treeWidget_data.topLevelItem(2).setText(0, _translate("MainWindow", "Parameters"))
        self.treeWidget_data.topLevelItem(3).setText(0, _translate("MainWindow", "Mask"))
        self.treeWidget_data.topLevelItem(4).setText(0, _translate("MainWindow", "Unwrapped"))
        self.treeWidget_data.topLevelItem(5).setText(0, _translate("MainWindow", "Tissue Phase"))
        self.treeWidget_data.topLevelItem(6).setText(0, _translate("MainWindow", "Susceptibility"))
        self.treeWidget_data.setSortingEnabled(__sortingEnabled)
        self.radioButton_data_left.setText(_translate("MainWindow", "Left"))
        self.radioButton_data_right.setText(_translate("MainWindow", "Right"))
        self.toolBox_main.setItemText(self.toolBox_main.indexOf(self.page_data), _translate("MainWindow", "Data"))
        self.treeWidget_parameters.headerItem().setText(0, _translate("MainWindow", "Parameter"))
        self.treeWidget_parameters.headerItem().setText(1, _translate("MainWindow", "Value"))
        __sortingEnabled = self.treeWidget_parameters.isSortingEnabled()
        self.treeWidget_parameters.setSortingEnabled(False)
        self.treeWidget_parameters.topLevelItem(0).setText(0, _translate("MainWindow", "Acquisition"))
        self.treeWidget_parameters.topLevelItem(0).child(0).setText(0, _translate("MainWindow", "echoes (TE)"))
        self.treeWidget_parameters.topLevelItem(0).child(0).setText(1, _translate("MainWindow", "1"))
        self.treeWidget_parameters.topLevelItem(0).child(1).setText(0, _translate("MainWindow", "voxel size"))
        self.treeWidget_parameters.topLevelItem(0).child(1).setText(1, _translate("MainWindow", "[1,1,1]"))
        self.treeWidget_parameters.topLevelItem(0).child(2).setText(0, _translate("MainWindow", "strength (B0)"))
        self.treeWidget_parameters.topLevelItem(0).child(2).setText(1, _translate("MainWindow", "3"))
        self.treeWidget_parameters.topLevelItem(0).child(3).setText(0, _translate("MainWindow", "direction (B0_dir)"))
        self.treeWidget_parameters.topLevelItem(0).child(3).setText(1, _translate("MainWindow", "[0,0,1]"))
        self.treeWidget_parameters.topLevelItem(1).setText(0, _translate("MainWindow", "V-SHARP"))
        self.treeWidget_parameters.topLevelItem(1).child(0).setText(0, _translate("MainWindow", "radius"))
        self.treeWidget_parameters.topLevelItem(1).child(0).setText(1, _translate("MainWindow", "12"))
        self.treeWidget_parameters.topLevelItem(2).setText(0, _translate("MainWindow", "QSM-STAR"))
        self.treeWidget_parameters.topLevelItem(2).child(0).setText(0, _translate("MainWindow", "tau"))
        self.treeWidget_parameters.topLevelItem(2).child(0).setText(1, _translate("MainWindow", "1e-6"))
        self.treeWidget_parameters.topLevelItem(3).setText(0, _translate("MainWindow", "QSM-iCS"))
        self.treeWidget_parameters.topLevelItem(3).child(0).setText(0, _translate("MainWindow", "alpha"))
        self.treeWidget_parameters.topLevelItem(3).child(0).setText(1, _translate("MainWindow", "5e-5"))
        self.treeWidget_parameters.topLevelItem(3).child(1).setText(0, _translate("MainWindow", "beta"))
        self.treeWidget_parameters.topLevelItem(3).child(1).setText(1, _translate("MainWindow", "3e-4"))
        self.treeWidget_parameters.topLevelItem(3).child(2).setText(0, _translate("MainWindow", "max iterations"))
        self.treeWidget_parameters.topLevelItem(3).child(2).setText(1, _translate("MainWindow", "10"))
        self.treeWidget_parameters.topLevelItem(3).child(3).setText(0, _translate("MainWindow", "tolerance"))
        self.treeWidget_parameters.topLevelItem(3).child(3).setText(1, _translate("MainWindow", "1"))
        self.treeWidget_parameters.setSortingEnabled(__sortingEnabled)
        self.toolBox_main.setItemText(self.toolBox_main.indexOf(self.page_parameters), _translate("MainWindow", "Parameters"))
        self.pushButton_create_mask.setText(_translate("MainWindow", "Create Mask"))
        self.pushButton_unwrap_phase.setText(_translate("MainWindow", "Unwrap Phase"))
        self.pushButton_v_sharp.setText(_translate("MainWindow", "V-SHARP"))
        self.pushButton_qsm_star.setText(_translate("MainWindow", "QSM-STAR"))
        self.pushButton_qsm_ics.setText(_translate("MainWindow", "QSM-iCS"))
        self.label.setText(_translate("MainWindow", "Center"))
        self.label_2.setText(_translate("MainWindow", "Range"))
        self.pushButton_contrast_auto.setText(_translate("MainWindow", "Auto"))
        self.pushButton_contrast_ok.setText(_translate("MainWindow", "OK"))
        self.pushButton_contrast_cancel.setText(_translate("MainWindow", "Cancel"))
        self.radioButton_contrast_left.setText(_translate("MainWindow", "Left"))
        self.radioButton_contrast_right.setText(_translate("MainWindow", "Right"))
        self.spinBox_all_x.setPrefix(_translate("MainWindow", "x: "))
        self.spinBox_all_y.setPrefix(_translate("MainWindow", "y: "))
        self.spinBox_all_z.setPrefix(_translate("MainWindow", "z: "))
        self.spinBox_all_v.setPrefix(_translate("MainWindow", "v: "))
        self.spinBox_single_v.setPrefix(_translate("MainWindow", "v: "))
        self.spinBox_single_slice_left.setPrefix(_translate("MainWindow", "Slice: "))
        self.spinBox_single_slice_right.setPrefix(_translate("MainWindow", "Slice: "))
        self.menuFile.setTitle(_translate("MainWindow", "File"))
        self.menuView.setTitle(_translate("MainWindow", "View"))
        self.menuOrientation.setTitle(_translate("MainWindow", "Orientation"))
        self.menuHelp.setTitle(_translate("MainWindow", "Help"))
        self.toolBar.setWindowTitle(_translate("MainWindow", "toolBar"))
        self.actionRead_Dicom.setText(_translate("MainWindow", "Read Dicom"))
        self.actionRead_Dicom.setToolTip(_translate("MainWindow", "Read Dicom"))
        self.actionAbout.setText(_translate("MainWindow", "About"))
        self.actionAbout.setToolTip(_translate("MainWindow", "About"))
        self.actionOpen.setText(_translate("MainWindow", "Open"))
        self.actionOpen.setToolTip(_translate("MainWindow", "Open"))
        self.actionSave.setText(_translate("MainWindow", "Save"))
        self.actionSave.setToolTip(_translate("MainWindow", "Save"))
        self.actionSave_All.setText(_translate("MainWindow", "Save All"))
        self.actionSave_All.setToolTip(_translate("MainWindow", "Save All"))
        self.actionSave_All.setShortcut(_translate("MainWindow", "Ctrl+S"))
        self.actionAxial.setText(_translate("MainWindow", "Axial"))
        self.actionAxial.setToolTip(_translate("MainWindow", "Axial"))
        self.actionSaggital.setText(_translate("MainWindow", "Saggital"))
        self.actionSaggital.setToolTip(_translate("MainWindow", "Saggital"))
        self.actionCoronal.setText(_translate("MainWindow", "Coronal"))
        self.actionCoronal.setToolTip(_translate("MainWindow", "Coronal"))
        self.actionAll_Orientations.setText(_translate("MainWindow", "All Orientations"))
        self.actionAll_Orientations.setToolTip(_translate("MainWindow", "All Orientations"))
        self.actionContrast.setText(_translate("MainWindow", "Contrast"))
        self.actionContrast.setToolTip(_translate("MainWindow", "Contrast"))
        self.actionZoom_In.setText(_translate("MainWindow", "Zoom In"))
        self.actionZoom_In.setToolTip(_translate("MainWindow", "Zoom In"))
        self.actionZoom_Out.setText(_translate("MainWindow", "Zoom Out"))
        self.actionZoom_Out.setToolTip(_translate("MainWindow", "Zoom Out"))
        self.actionView.setText(_translate("MainWindow", "View"))
        self.actionView.setToolTip(_translate("MainWindow", "View"))

import qsm_images_rc

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

